staging:
  base_url: "https://jsonplaceholder.typicode.com"
  ui_url: "https://www.saucedemo.com"
  timeout: 30
  headless: true

prod:
  base_url: "https://jsonplaceholder.typicode.com"
  ui_url: "https://www.saucedemo.com"
  timeout: 30
  headless: true